export const ANONYMOUS = 'ANONYMOUS';
export const CURRENT_MEMBER = 'CURRENT_MEMBER';

export const MAIN_VIEW = 'MAIN_VIEW';
export const WHO_IS_WATCHING_VIEW = 'WHO_IS_WATCHING_VIEW';
export const MANAGE_PROFILES_VIEW = 'MANAGE_PROFILES_VIEW';
