export enum Type {
  START_TO_CHECK_WHICH_VIEW_OF_GUEST_OR_MEMBER = 'START_TO_CHECK_WHICH_VIEW_OF_GUEST_OR_MEMBER',
  GET_NETFLIX_USER_INFO = 'GET_NETFLIX_USER_INFO',
  POST_NETFLIX_USER_INFO = 'POST_NETFLIX_USER_INFO',
  GET_NETFLIX_PROFILE_GATE_STATE = 'GET_NETFLIX_PROFILE_GATE_STATE',
  POST_NETFLIX_PROFILE_GATE_STATE = 'POST_NETFLIX_PROFILE_GATE_STATE',
}
