export const START_TO_CHECK_WHICH_VIEW_OF_GUEST_OR_MEMBER =
  'START_TO_CHECK_WHICH_VIEW_OF_GUEST_OR_MEMBER';
export const START_TO_CHECK_WHICH_VIEW_OF_MAIN_OR_OTHER =
  'START_TO_CHECK_WHICH_VIEW_OF_MAIN_OR_OTHER';

export const GET_NETFLIX_USER_INFO = 'GET_NETFLIX_USER_INFO';
export const POST_NETFLIX_USER_INFO = 'POST_NETFLIX_USER_INFO';

export const GET_NETFLIX_PROFILE_GATE_STATE = 'GET_NETFLIX_PROFILE_GATE_STATE';
export const POST_NETFLIX_PROFILE_GATE_STATE =
  'POST_NETFLIX_PROFILE_GATE_STATE';
