name: Node.js Testing CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: mkdir build-test
      - run: npm ci

      - name: Run Build
        run: |
          echo 'TEST_NODE_ENV ${{env.TEST_NODE_ENV}}'
          npm run build

      - name: Run Tests
        run: |
          echo 'TEST_NODE_ENV ${{env.TEST_NODE_ENV}}'
          npm test
        env:
          TEST_BUILD_PATH: ./build-test
          TEST_NODE_ENV: test
