name: Node.js Testing CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_PATH: ./build-test
  TEST_NODE_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: mkdir build-test
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
